// <auto-generated />
using System;
using ConsumerPoints.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsumerPoints.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210601185431_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsumerPoints.Models.PayerPoints", b =>
                {
                    b.Property<string>("Payer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Payer");

                    b.ToTable("PayerPoints");
                });

            modelBuilder.Entity("ConsumerPoints.Models.SpendingMarker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LastSpentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LastWasPartiallySpent")
                        .HasColumnType("bit");

                    b.Property<int>("Remainder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SpendingMarkers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastSpentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastWasPartiallySpent = false,
                            Remainder = 0
                        });
                });

            modelBuilder.Entity("ConsumerPoints.Models.Transaction", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Timestamp");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
