// <auto-generated />
using System;
using ConsumerPoints.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsumerPoints.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210601172410_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConsumerPoints.Models.PayerPoints", b =>
                {
                    b.Property<string>("Payer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Payer");

                    b.ToTable("PayerPoints");

                    b.HasData(
                        new
                        {
                            Payer = "cvs pharmacy",
                            Points = 600
                        });
                });

            modelBuilder.Entity("ConsumerPoints.Models.Transaction", b =>
                {
                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("Timestamp");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Timestamp = new DateTime(2021, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payer = "CVS Pharmacy",
                            Points = 400
                        },
                        new
                        {
                            Timestamp = new DateTime(2021, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payer = "CVS Pharmacy",
                            Points = 200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
